name: deploy_action

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo project_id
        run: echo "project-id" 
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            project_id: ${{ secrets.gcp_project }}
            service_account_key: ${{ secrets.gcp_credentials }}
            export_default_credentials: true   
            service_account_email: sa-function@project1-277418.iam.gserviceaccount.com
      - name: Deploy a Cloud Function v1
        run: | 
          echo "MEMBER" $MEMBER
          gcloud functions deploy hello_get --runtime python38 --trigger-http --allow-unauthenticated  
          
      - name: Deploy a Cloud Function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: hello_get
          runtime: Python 3.7
          entry_point: hello_get
          project_id: ${{ secrets.gcp_project }}
          credentials: ${{ secrets.gcp_credentials }}      
      - name: completed deploying
        run: echo "deployed"