name: deploy_action

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo project_id
        run: echo "project-id" 
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            project_id: ${{ secrets.gcp_project }}
            service_account_key: ${{ secrets.gcp_credentials }}
            export_default_credentials: true   
            service_account_email: sa-function@project1-277418.iam.gserviceaccount.com
      - name: checkout
        uses: actions/checkout@v1    
      - name: getting account
        run: gcloud config list account      
      - name: activating account
        run: gcloud auth activate-service-account sa-function@project1-277418.iam.gserviceaccount.com --key-file=SA-file.json        
      - name: getting account
        run: gcloud config list account
      - name: getting files
        run: |
          pwd
          ls -a     
      - name: app-deploy
        run: gcloud functions deploy hello_get --runtime python38 --trigger-http
